"""init

Revision ID: ff9822c8c166
Revises: 65f82af682ab
Create Date: 2025-05-16 12:44:15.995850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9822c8c166'
down_revision = '65f82af682ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
